### PR TITLE
made CIE work and updated readme

### PR DESCRIPTION
**Pull request by anuragrao04**
updated readme to reflect new repo name 'scraper' instead of 'ec-scraper'

Removed line 48 that was overriding the sem value, rendering the CIE fix useless

### CODE REVIEW

**Comment by anuragrao04** [comment]
wait don't merge-

**Comment by anuragrao04** [comment]
should work now

**Comment by anuragrao04** [comment]
should really work now

**Review by alfadelta10010 — APPROVED** [review]
looks good

**Comment by alfadelta10010** [comment]
thanks a lot @anuragrao04

**Pull request merged**
